services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j:7474
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    depends_on:
      - neo4j
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5001:5000"
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8000:80"
    networks:
      - app-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  app-network:
    driver: bridge